[repository]
name = "hyprmagnet"
authors = ["Dregu"]
#commit_pins = []

[hyprmagnet]
description = "Move mouse events from just outside a tiled window (i.e. from outer gaps and borders) to just inside the window, to click browser tabs and scrollbars without having to aim inside the window."
authors = ["Dregu"]
output = "libhyprmagnet.so"
build = ["make"]
